import type { ZodISODateTime, ZodLiteral, ZodObject, ZodOptional, ZodString } from 'zod/v4'
import { z } from 'zod/v4'
import { MESSAGE_DEDUPLICATION_OPTIONS_SCHEMA } from '../messages/messageDeduplicationSchemas.ts'

// External message metadata that describe the context in which the message was created, primarily used for debugging purposes
export const PUBLISHER_MESSAGE_METADATA_SCHEMA = z
  .object({
    schemaVersion: z.optional(z.string().min(1).describe('message schema version')),
    // this is always set to a service that created the message
    producedBy: z.optional(z.string().min(1).describe('app/service that produced the message')),
    // this is always propagated within the message chain. For the first message in the chain it is equal to "producedBy"
    originatedFrom: z.optional(
      z
        .string()
        .min(1)
        .describe('app/service that initiated entire workflow that led to creating this message'),
    ),
    // this is always propagated within the message chain.
    correlationId: z.optional(
      z.string().describe('unique identifier passed to all events in workflow chain'),
    ),
  })
  .describe('external message metadata')

export const CONSUMER_MESSAGE_METADATA_SCHEMA = z
  .object({
    schemaVersion: z.string().min(1).describe('message schema version'),
    // this is always set to a service that created the message
    producedBy: z.string().min(1).describe('app/service that produced the message'),
    // this is always propagated within the message chain. For the first message in the chain it is equal to "producedBy"
    originatedFrom: z
      .string()
      .min(1)
      .describe('app/service that initiated entire workflow that led to creating this message'),
    // this is always propagated within the message chain.
    correlationId: z.string().describe('unique identifier passed to all events in workflow chain'),
  })
  .describe('external message metadata')

// Base event fields that are typically autogenerated
export const GENERATED_BASE_EVENT_SCHEMA = z.object({
  id: z.string().describe('event unique identifier'),
  timestamp: z.iso.datetime().describe('iso 8601 datetime'),
  deduplicationId: z.string().nullish().describe('event deduplication identifier'),
  deduplicationOptions: MESSAGE_DEDUPLICATION_OPTIONS_SCHEMA.nullish().describe(
    'event deduplication options',
  ),
  // For internal domain events that did not originate within a message chain metadata field can be omitted, producer should then assume it is initiating a new chain
  metadata: CONSUMER_MESSAGE_METADATA_SCHEMA,
})

// Base event fields that are typically autogenerated, marked as optional
export const OPTIONAL_GENERATED_BASE_EVENT_SCHEMA = z.object({
  id: z.string().describe('event unique identifier').optional(),
  timestamp: z.iso.datetime().describe('iso 8601 datetime').optional(),
  deduplicationId: z.string().describe('event deduplication identifier').nullish(),
  deduplicationOptions: MESSAGE_DEDUPLICATION_OPTIONS_SCHEMA.describe(
    'event deduplication options',
  ).nullish(),
  // For internal domain events that did not originate within a message chain metadata field can be omitted, producer should then assume it is initiating a new chain
  metadata: PUBLISHER_MESSAGE_METADATA_SCHEMA.optional(),
})

// Base event fields that are always defined manually
export const CORE_EVENT_SCHEMA = z.object({
  type: z.literal<string>('<replace.me>').describe('event type name'),
  payload: z.looseObject({}).describe('event payload based on type'),
})

// Core fields that describe either internal event or external message
export const CONSUMER_BASE_EVENT_SCHEMA = z.object({
  ...GENERATED_BASE_EVENT_SCHEMA.shape,
  ...CORE_EVENT_SCHEMA.shape,
})
export const PUBLISHER_BASE_EVENT_SCHEMA = z.object({
  ...OPTIONAL_GENERATED_BASE_EVENT_SCHEMA.shape,
  ...CORE_EVENT_SCHEMA.shape,
})

export type ConsumerBaseEventType = z.output<typeof CONSUMER_BASE_EVENT_SCHEMA>
export type PublisherBaseEventType = z.output<typeof PUBLISHER_BASE_EVENT_SCHEMA>
export type CoreEventType = z.output<typeof CORE_EVENT_SCHEMA>
export type GeneratedBaseEventType = z.output<typeof GENERATED_BASE_EVENT_SCHEMA>

/**
 * Schema allowed as an event/message payload: anything whose input and output are objects, which
 * covers a plain object schema and a union of object variants (e.g. a single-item / multi-item
 * shape). It stays object-based (a bare string/number payload is not allowed) while accepting
 * unions. Defined via the input/output types (not `ZodObject | ZodUnion`) so `.extend` does not
 * distribute over a type-level union and collapse it back to a plain object.
 *
 * Both the output AND input type parameters are pinned: leaving `Input` at its default `unknown`
 * would widen `z.input<publisherSchema>['payload']` to `unknown`, dropping the object-payload
 * guarantee for code written generically over CommonEventDefinition, and would let scalar-input
 * transforms (e.g. `z.preprocess`) through.
 */
export type EventPayloadSchema = z.ZodType<Record<string, unknown>, Record<string, unknown>>

type IsAny<T> = 0 extends 1 & T ? true : false

/**
 * A payload schema whose output is `any` (e.g. `z.any()`) satisfies EventPayloadSchema, because
 * `any` is assignable to `Record<string, unknown>`, yet it silently disables payload type-checking
 * for every handler and publisher of the event. Intersecting the payload parameter with this
 * collapses it to `never` for such a schema, rejecting the call, while leaving real payloads
 * (objects, unions of objects, transforms to objects) untouched.
 */
export type RejectAnyPayload<T extends EventPayloadSchema> =
  IsAny<z.output<T>> extends true ? never : unknown

type ReturnType<T extends EventPayloadSchema, Z extends string> = {
  consumerSchema: ZodObject<{
    id: ZodString
    timestamp: ZodISODateTime
    type: ZodLiteral<Z>
    payload: T
  }>

  publisherSchema: ZodObject<{
    id: ZodOptional<ZodString>
    timestamp: ZodOptional<ZodISODateTime>
    type: ZodLiteral<Z>
    payload: T
  }>
}

export function enrichEventSchemaWithBase<T extends EventPayloadSchema, Z extends string>(
  type: Z,
  payloadSchema: T & RejectAnyPayload<T>,
): ReturnType<T, Z> {
  const baseSchema = z.object({
    type: z.literal(type),
    payload: payloadSchema,
  })

  const consumerSchema = z.object({
    ...GENERATED_BASE_EVENT_SCHEMA.shape,
    ...baseSchema.shape,
  })
  const publisherSchema = z.object({
    ...OPTIONAL_GENERATED_BASE_EVENT_SCHEMA.shape,
    ...baseSchema.shape,
  })

  return {
    consumerSchema: consumerSchema,
    publisherSchema: publisherSchema,
  }
}
