services:
  localstack:
    image: localstack/localstack:4.0.2
    network_mode: bridge
    hostname: localstack
    ports:
      - '127.0.0.1:4566:4566' # LocalStack Gateway
      - '127.0.0.1:4510-4559:4510-4559' # external services port range
    environment:
      - SERVICES=sqs,s3
      - DEBUG=0
      - DATA_DIR=${DATA_DIR-}
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LOCALSTACK_HOST=localstack
    #      - LOCALSTACK_API_KEY=someDummyKey
    volumes:
      - '${TMPDIR:-/tmp}/localstack:/var/log/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'
