services:
  redis:
    image: redis:6.2.7-alpine
    command: redis-server --requirepass sOmE_sEcUrE_pAsS
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/redis/data:cached
    restart: on-failure

volumes:
  redis_data:
    driver: local
