services:
  rabbitmq:
    image: rabbitmq:4.0.4
    ports:
      - ${DOCKER_RABBITMQ_CLIENT_PORT:-5672}:5672
      - ${DOCKER_RABBITMQ_MANAGEMENT_PORT:-15672}:15672
    volumes:
      - rabbit_data:/var/lib/rabbitmq

volumes:
  rabbit_data:
    driver: local
