name: CI Kafka

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  call-ci-flow:
    strategy:
      matrix:
        node-version: [22.x ]
    uses: kibertoad/message-queue-toolkit/.github/workflows/ci.common.yml
    with:
      working_directory: 'packages/amqp'
      node_version: ${{ matrix.node-version }}
