name: Kafka - confluentinc-kafka-javascript performance test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: Install
        run: npm install --ignore-scripts

      # We need to run @confluentinc/kafka-javascript scripts
      - name: Run confluentinc kafka-javascript scripts
        working-directory: packages/kafka
        run: npm rebuild @confluentinc/kafka-javascript

      - name: Docker start
        run: npm run docker:start:ci -- --filter=@message-queue-toolkit/kafka

      - name: Build TS
        run: npm run build

      - name: Run Tests
        run: npm run test:ci -- --filter=@message-queue-toolkit/kafka

      - name: Docker stop
        run: npm run docker:stop:ci -- --filter=@message-queue-toolkit/kafka
